GOOGLE_API_KEY = "AIzaSyAj5-Z---8BEn-eQSw9SgEw86ilqpsDzuI"
MAPS_API_KEY = "AIzaSyAu1-MzkeW6S-CwF7XkaKnC_-azMMbBBek"

[postgres]
host = "ep-long-tooth-a1v341ql-pooler.ap-southeast-1.aws.neon.tech"
port = 5432
dbname = "neondb"
user = "neondb_owner"
password = "npg_pODmXjg5L6Kv"
sslmode = "require"
